LOCK TABLES `category_animals` WRITE;
INSERT INTO `category_animals` (`fk_family_id`, `name`, `description`) VALUES
(1, 'Lapin', "Les lapins ont une apparence caractéristique avec leurs longues oreilles dressées, leur corps trapu et leur queue touffue. Voici quelques caractéristiques physiques des lapins : Poids : les lapins pèsent en moyenne entre 1,5 et 2,5 kilogrammes, mais certaines races peuvent peser jusqu'à 5 kilos."),
(1, 'Rat', "Le mot « rat » est un nom vernaculaire ambigu qui peut désigner, en français, des centaines d'espèces différentes dans le monde de mammifères rongeurs omnivores, dont la queue est nue, les dents tranchantes et le museau pointu."),
(1, 'Souris',"« Souris » est un nom du vocabulaire courant qui peut désigner toutes sortes de mammifères rongeurs ayant généralement une petite taille, un museau pointu, des oreilles rondes, un pelage gris-brun et une queue relativement longue."),
(1, "Cochon d'inde","Sociable et attendrissant, le cochon d'Inde est un animal de compagnie idéal et terriblement attachant pour les petits comme pour les grands. Du haut de ses 12 à 35 cm pour un petit pois de 500 grammes à 1,7 kg, le cochon d'Inde est une boule de poils qui appartient à la famille des rongeurs."),
(2, 'Pie bavarde', "La Pie bavarde est un grand corvidé noir et blanc à longue queue. L'adulte a la tête, la poitrine, le dos et le bas-ventre noirs. Les ailes et la queue présentent un plumage bleu-vert métallique. L'abdomen est d'un blanc pur."),
(2, 'Merle noir', "Longueur 24 cm, envergure 38 cm, poids moyen 100 g. Diagnose : Le mâle est uniformément noir avec un bec et un cercle oculaire jaune orangé. La femelle est brune et tachetée (la Grive musicienne est également tachetée dessous, mais la couleur de fond de sa poitrine est beaucoup plus claire)."),
(2, 'Mésange bleue', "Longueur 11,5 cm, envergure 17,5-20 cm, poids 9-12 g. Elle vit dans une grande variété d'habitats mais reste globalement liée aux boisements de feuillus à basse altitude. Elle s'adapte aux taillis, aux parcs et aux jardins si elle y trouve des cavités de nidification."),
(3, 'Anchois', "Les anchois sont de petits poissons fourrages d'eau salée communs de la famille des Engraulidae qui sont utilisés comme nourriture humaine et comme appât pour les poissons. Il existe 144 espèces réparties en 17 genres dans les océans Atlantique, Indien et Pacifique."),
(3, 'Poisson rouge', "Cette espèce mesure généralement de 20 à 30 cm et peut peser 1 kg. Diagnose : Il existe de nombreuses variétés créées par l'Homme. Dans sa forme rustique, le carassin doré (ou communément appelé poisson-rouge) a une grosse tête, une longue nageoire dorsale convexe armée d'un rayon dur et denté."),
(4, 'Lézard', "Reptile saurien (de la famille des Lacertidés) généralement de petite taille, au corps allongé, recouvert d'écailles, à quatre pattes courtes et grêles et dont la queue est longue, effilée et cassante."),
(4, 'Tortue', "Parmi les plus anciens reptiles vivants, les tortues terrestres compte environ 75 espèces différentes. D'ailleurs, elles ont très peu évolué physiquement depuis leur arrivée sur terre : elles possèdent une carapace bombée (qui peut faire le double de leur poids) et des pattes épaisses surmontées de griffes."),
(null, 'Chien', "Le Chien est la sous-espèce domestique de Canis lupus, un mammifère de la famille des Canidés, laquelle comprend également le dingo, chien domestique retourné à l'état sauvage."),
(null, 'Chat', "Le chat domestique est une espèce de mammifères carnivores, de la famille des Félidés. Issu de la domestication du chat sauvage Felis silvestris, il était anciennement considéré comme une sous-espèce de celui-ci, sous la dénomination Felis silvestris catus.");
UNLOCK TABLES;