LOCK TABLES `departments` WRITE;
INSERT INTO `departments` (`region_code`, `code`, `name`, `slug`) VALUES
('84', '01', 'Ain', 'ain'),
('32', '02', 'Aisne', 'aisne'),
('84', '03', 'Allier', 'allier'),
('93', '04', 'Alpes-de-Haute-Provence', 'alpes de haute provence'),
('93', '05', 'Hautes-Alpes', 'hautes alpes'),
('93', '06', 'Alpes-Maritimes', 'alpes maritimes'),
('84', '07', 'Ardèche', 'ardeche'),
('44', '08', 'Ardennes', 'ardennes'),
('76', '09', 'Ariège', 'ariege'),
('44', '10', 'Aube', 'aube'),
('76', '11', 'Aude', 'aude'),
('76', '12', 'Aveyron', 'aveyron'),
('93', '13', 'Bouches-du-Rhône', 'bouches du rhone'),
('28', '14', 'Calvados', 'calvados'),
('84', '15', 'Cantal', 'cantal'),
('75', '16', 'Charente', 'charente'),
('75', '17', 'Charente-Maritime', 'charente maritime'),
('24', '18', 'Cher', 'cher'),
('75', '19', 'Corrèze', 'correze'),
('27', '21', 'Côte-d\'Or', 'cote dor'),
('53', '22', 'Côtes-d\'Armor', 'cotes darmor'),
('75', '23', 'Creuse', 'creuse'),
('75', '24', 'Dordogne', 'dordogne'),
('27', '25', 'Doubs', 'doubs'),
('84', '26', 'Drôme', 'drome'),
('28', '27', 'Eure', 'eure'),
('24', '28', 'Eure-et-Loir', 'eure et loir'),
('53', '29', 'Finistère', 'finistere'),
('94', '2A', 'Corse-du-Sud', 'corse du sud'),
('94', '2B', 'Haute-Corse', 'haute corse'),
('76', '30', 'Gard', 'gard'),
('76', '31', 'Haute-Garonne', 'haute garonne'),
('76', '32', 'Gers', 'gers'),
('75', '33', 'Gironde', 'gironde'),
('76', '34', 'Hérault', 'herault'),
('53', '35', 'Ille-et-Vilaine', 'ille et vilaine'),
('24', '36', 'Indre', 'indre'),
('24', '37', 'Indre-et-Loire', 'indre et loire'),
('84', '38', 'Isère', 'isere'),
('27', '39', 'Jura', 'jura'),
('75', '40', 'Landes', 'landes'),
('24', '41', 'Loir-et-Cher', 'loir et cher'),
('84', '42', 'Loire', 'loire'),
('84', '43', 'Haute-Loire', 'haute loire'),
('52', '44', 'Loire-Atlantique', 'loire atlantique'),
('24', '45', 'Loiret', 'loiret'),
('76', '46', 'Lot', 'lot'),
('75', '47', 'Lot-et-Garonne', 'lot et garonne'),
('76', '48', 'Lozère', 'lozere'),
('52', '49', 'Maine-et-Loire', 'maine et loire'),
('28', '50', 'Manche', 'manche'),
('44', '51', 'Marne', 'marne'),
('44', '52', 'Haute-Marne', 'haute marne'),
('52', '53', 'Mayenne', 'mayenne'),
('44', '54', 'Meurthe-et-Moselle', 'meurthe et moselle'),
('44', '55', 'Meuse', 'meuse'),
('53', '56', 'Morbihan', 'morbihan'),
('44', '57', 'Moselle', 'moselle'),
('27', '58', 'Nièvre', 'nievre'),
('32', '59', 'Nord', 'nord'),
('32', '60', 'Oise', 'oise'),
('28', '61', 'Orne', 'orne'),
('32', '62', 'Pas-de-Calais', 'pas de calais'),
('84', '63', 'Puy-de-Dôme', 'puy de dome'),
('75', '64', 'Pyrénées-Atlantiques', 'pyrenees atlantiques'),
('76', '65', 'Hautes-Pyrénées', 'hautes pyrenees'),
('76', '66', 'Pyrénées-Orientales', 'pyrenees orientales'),
('44', '67', 'Bas-Rhin', 'bas rhin'),
('44', '68', 'Haut-Rhin', 'haut rhin'),
('84', '69', 'Rhône', 'rhone'),
('27', '70', 'Haute-Saône', 'haute saone'),
('27', '71', 'Saône-et-Loire', 'saone et loire'),
('52', '72', 'Sarthe', 'sarthe'),
('84', '73', 'Savoie', 'savoie'),
('84', '74', 'Haute-Savoie', 'haute savoie'),
('11', '75', 'Paris', 'paris'),
('28', '76', 'Seine-Maritime', 'seine maritime'),
('11', '77', 'Seine-et-Marne', 'seine et marne'),
('11', '78', 'Yvelines', 'yvelines'),
('75', '79', 'Deux-Sèvres', 'deux sevres'),
('32', '80', 'Somme', 'somme'),
('76', '81', 'Tarn', 'tarn'),
('76', '82', 'Tarn-et-Garonne', 'tarn et garonne'),
('93', '83', 'Var', 'var'),
('93', '84', 'Vaucluse', 'vaucluse'),
('52', '85', 'Vendée', 'vendee'),
('75', '86', 'Vienne', 'vienne'),
('75', '87', 'Haute-Vienne', 'haute vienne'),
('44', '88', 'Vosges', 'vosges'),
('27', '89', 'Yonne', 'yonne'),
('27', '90', 'Territoire de Belfort', 'territoire de belfort'),
('11', '91', 'Essonne', 'essonne'),
('11', '92', 'Hauts-de-Seine', 'hauts de seine'),
('11', '93', 'Seine-Saint-Denis', 'seine saint denis'),
('11', '94', 'Val-de-Marne', 'val de marne'),
('11', '95', 'Val-d\'Oise', 'val doise'),
('01', '971', 'Guadeloupe', 'guadeloupe'),
('02', '972', 'Martinique', 'martinique'),
('03', '973', 'Guyane', 'guyane'),
('04', '974', 'La Réunion', 'la reunion'),
('06', '976', 'Mayotte', 'mayotte'),
('COM', '975', 'Saint-Pierre-et-Miquelon', 'saint pierre et miquelon'),
('COM', '977', 'Saint-Barthélemy', 'saint barthelemy'),
('COM', '978', 'Saint-Martin', 'saint martin'),
('COM', '984', 'Terres australes et antarctiques françaises', 'terres australes et antarctiques francaises'),
('COM', '986', 'Wallis et Futuna', 'wallis et futuna'),
('COM', '987', 'Polynésie française', 'polynesie francaise'),
('COM', '988', 'Nouvelle-Calédonie', 'nouvelle caledonie'),
('COM', '989', 'Île de Clipperton', 'ile de clipperton');
UNLOCK TABLES;