name: CD
on: 
  push:
    branches: [test]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SSHPASS: ${{ secrets.APP_PASS }}

    steps:
      - uses: actions/checkout@v2
          
      - name: SSHPASS and DEPLOY project
        run:  
          sshpass -p ${{ secrets.APP_PASS }} ssh -o stricthostkeychecking=no -p 5022 ${{ secrets.APP_USER }}@${{ secrets.APP_HOST }}
          "cd tatanimo.mds-lille.yt/ &&
          git pull origin preprod &&
          /home/gxxgzxxc/composer.phar install &&
          php bin/console d:m:m -n"
