name: CD
on: 
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SSHPASS: ${{ secrets.APP_PASS }}

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v6

      - name: Install dependencies  # Étape pour installer les dépendances npm
        run: sudo npm install

      - name: copy node modules files via FTP
        uses: airvzxf/ftp-deployment-action@latest
        with:
          server: ${{ secrets.APP_IP }}
          user: ${{ secrets.APP_USER }}
          password: ${{ secrets.APP_PASS }}
          local_dir: "./node_modules"
          remote_dir: "/tatanimo.mds-lille.yt/node_modules"

      - name: Build  # Étape pour exécuter npm run build
        run: npm run build
          
      - name: SSHPASS and DEPLOY project
        run:  
          sshpass -e ssh -o stricthostkeychecking=no ${{ secrets.APP_USER }}@${{ secrets.APP_HOST }}
          "cd tatanimo.mds-lille.yt/ &&
          git stash &&
          git pull origin master &&
          php bin/console init:db --no-interaction &&
          php bin/console cache:clear"
