name: CD
on: 
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SSHPASS: ${{ secrets.APP_PASS }}

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v6

      - name: Install dependencies  # Étape pour installer les dépendances npm
        run: npm install

      - name: Build  # Étape pour exécuter npm run build
        run: npm run build
          
      - name: SSHPASS and DEPLOY project
        run:  |
          sshpass -e ssh -o stricthostkeychecking=no ${{ secrets.APP_USER }}@${{ secrets.APP_HOST }} \
          "cd tatanimo.mds-lille.yt/ && \
          git stash && \
          git pull origin master && \
          /home/gxxgzxxc/composer.phar install && \
          php bin/console init:db --no-interaction && \
          php bin/console cache:clear"
