name: CD
on: 
  push:
    branches: [preprod]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SSHPASS: ${{ secrets.APP_PASS }}

    steps:
      - uses: actions/checkout@v2
          
      - name: APT UPDATE and INSTALL SSHPASS
        run:  
          sshpass -e ssh -o stricthostkeychecking=no -p 5022 gxxgzxxc@185.221.182.104
          "cd tatanimo.mds-lille.yt/ &&
          git fetch origin preprod &&
          git reset --hard origin preprod &&
          composer install &&
          npm install &&
          npm run build &&
          php bin/console d:m:m -n"
