name: CD
on: 
  push:
    branches: [test]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SSHPASS: ${{ secrets.APP_PASS }}

    steps:
      - uses: actions/checkout@v2
          
      - name: SSHPASS and DEPLOY project
        run:  
          sshpass -e ssh -o stricthostkeychecking=no ${{ secrets.APP_USER }}@${{ secrets.APP_HOST }}
          "cd tatanimo.mds-lille.yt/ &&
          git pull origin test &&
          /home/gxxgzxxc/composer.phar install &&
          nvm use 16 &&
          npm install &&
          npm run build &&
          php bin/console d:d:d --force &&
          php bin/console d:d:c &&
          php bin/console d:m:m --no-interaction &&
          mysql -u '${{ secrets.DATABASE_USER }}' -p'${{ secrets.DATABASE_PASSWORD }}' --default-character-set=utf8 ${{ secrets.DATABASE_NAME }} < \database\regions.sql &&
          mysql -u '${{ secrets.DATABASE_USER }}' -p'${{ secrets.DATABASE_PASSWORD }}' --default-character-set=utf8 ${{ secrets.DATABASE_NAME }} < \database\departments.sql &&
          mysql -u '${{ secrets.DATABASE_USER }}' -p'${{ secrets.DATABASE_PASSWORD }}' --default-character-set=utf8 ${{ secrets.DATABASE_NAME }} < \database\cities.sql"
