name: CD
on: 
  push:
    branches: [preprod]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SSHPASS: ${{ secrets.APP_PASS }}

    steps:
      - uses: actions/checkout@v2
          
      - name: APT UPDATE and INSTALL SSHPASS
        run:  
          sshpass -p ${{ secrets.APP_PASS }} ssh -o stricthostkeychecking=no -p 5022 ${{ secrets.APP_USER }}@${{ secrets.APP_HOST }}
          "source ~/.bashrc &&
          cd tatanimo.mds-lille.yt/ &&
          git pull origin preprod &&
          composer install &&
          php bin/console d:m:m -n"
