name: CD
on: 
  push:
    branches: [test]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SSHPASS: ${{ secrets.APP_PASS }}

    steps:
      - uses: actions/checkout@v2
          
      - name: SSHPASS and DEPLOY project
        run:  
          sshpass -p ${{ secrets.APP_PASS }} ssh -o stricthostkeychecking=no -P 5022 ${{ secrets.APP_USER }}@185.221.182.104
          "cd tatanimo.mds-lille.yt/ &&
          git pull origin test &&
          /home/gxxgzxxc/composer.phar install &&
          npm install &&
          npm run build &&
          php bin/console d:m:m -n"
